# @package _global_
module:
  _target_: emg2qwerty.lightning.LSTMGRUCTCModule
  lstm_layers: 2
  lstm_hidden_size: 192
  lstm_dropout: 0.3
  between_dropout: 0.3
  gru_layers: 1
  gru_hidden_size: 64
  gru_bidirectional: True

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000  # 4 sec windows for 2kHz EMG
  padding: [1800, 200]  # 900ms past context, 100ms future context
