# @package _global_
module:
  _target_: emg2qwerty.lightning.LSTMGRUCTCModule
  lstm_hidden_size: 256
  lstm_layers: 3
  gru_hidden_size: 256
  gru_layers: 2

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000  # 4 sec windows for 2kHz EMG
  padding: [1800, 200]  # 900ms past context, 100ms future context
