# @package _global_
module:
  _target_: emg2qwerty.lightning.TCNCTCModule
  num_filters: [128, 128, 128, 256]
  kernel_size: 32
  dilation_base: 3

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000  # 4 sec windows for 2kHz EMG
  padding: [1800, 200]  # 900ms past context, 100ms future context
